[general]
debug = false
cursor = "_"
show_cursor = true
blink_cursor = true
user_name = "kishikuun"
fps = 15
color_scheme = "kishikuun"

[files]
frame_base_name = "frame_"
frame_folder_name = "frames"
output_gif_name = "terminal"
